
services:
  backend:
    build: ./backend
    container_name: cm_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    volumes:
      - ./backend/app:/usr/src/app/app
    depends_on:
      timescaledb:
        condition: service_healthy

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: cm_timescaledb
    environment:
      POSTGRES_USER: cm_user
      POSTGRES_PASSWORD: cm_pass
      POSTGRES_DB: cm_db
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro # binds the local /sql directory to the container's init directory. :ro avoids accidental container writes.
      - ./pgdata:/var/lib/postgresql/data # This is for persistent data storage
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cm_user -d cm_db"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  mqtt_network:
    driver: bridge
